{% set name = "git-machete" %}
{% set version = "3.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/git-machete-{{ version }}.tar.gz
  sha256: 8f8ee2b892b8b0840eef8f41145b76802637efd86aac3ccbb7935be06fbaa83d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=2.7

test:
  imports:
    - git_machete
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VirtusLab/git-machete
  summary: Probably the sharpest git repository organizer & rebase/merge workflow automation tool you've ever seen
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
